name: Build static site
description: ""

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: file-text
  color: purple

inputs:
  info:
    description: Directory that contains info files
    required: true
  media:
    description: Directory that contains media files
    required: true
  output:
    description: Directory to output static site
    required: true
  num_workers:
    description: Number of workers to use
    required: false
    default: "4"

runs:
  using: docker
  image: docker://ghcr.io/alsosee/finder:latest
