package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type RedirectRule struct {
	From   string `json:"from"`
	To     string `json:"to"`
	Status int    `json:"status"`
}

type WorkerRedirectsProjector struct {
	infoDir string
	output  string
}

func (p WorkerRedirectsProjector) Name() string {
	return "worker-redirects"
}

func (p WorkerRedirectsProjector) Run(_ *BuildGraph) error {
	rules, err := ParseRedirectsFile(filepath.Join(p.infoDir, "_redirects"))
	if err != nil {
		return err
	}

	if err := WriteWorkerRedirectsModule(p.output, rules); err != nil {
		return err
	}

	if len(rules) == 0 {
		log.Printf("No _redirects file found; generated empty Worker redirect table at %q", p.output)
		return nil
	}

	log.Printf("Generated %d Worker redirects from _redirects:", len(rules))
	for _, rule := range rules {
		log.Printf("%d %s -> %s", rule.Status, rule.From, rule.To)
	}

	return nil
}

func ParseRedirectsFile(path string) ([]RedirectRule, error) {
	b, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading redirects file: %w", err)
	}

	return ParseRedirects(string(b), path)
}

func ParseRedirects(source, name string) ([]RedirectRule, error) {
	var rules []RedirectRule
	for index, rawLine := range strings.Split(source, "\n") {
		line := strings.TrimSpace(stripRedirectComment(rawLine))
		if line == "" {
			continue
		}

		parts := strings.Fields(line)
		if len(parts) < 2 || len(parts) > 3 {
			return nil, fmt.Errorf("%s:%d: expected \"from to [status]\"", name, index+1)
		}

		status := 301
		if len(parts) == 3 {
			parsed, err := strconv.Atoi(parts[2])
			if err != nil {
				return nil, fmt.Errorf("%s:%d: status must be a 3xx integer", name, index+1)
			}
			status = parsed
		}

		rule := RedirectRule{From: parts[0], To: parts[1], Status: status}
		if err := validateRedirectRule(rule, name, index+1); err != nil {
			return nil, err
		}
		rules = append(rules, rule)
	}

	return rules, nil
}

func WriteWorkerRedirectsModule(path string, rules []RedirectRule) error {
	if path == "" {
		return fmt.Errorf("worker redirects output path is required")
	}
	if rules == nil {
		rules = []RedirectRule{}
	}

	b, err := json.MarshalIndent(rules, "", "  ")
	if err != nil {
		return fmt.Errorf("marshaling redirects: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("creating redirects output directory: %w", err)
	}

	body := strings.Join([]string{
		"// Generated by Finder. Do not edit.",
		fmt.Sprintf("export const REDIRECTS = %s;", string(b)),
		fmt.Sprintf("export const HAS_REDIRECTS = %t;", len(rules) > 0),
		"",
	}, "\n")

	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return fmt.Errorf("writing redirects module: %w", err)
	}

	return nil
}

func validateRedirectRule(rule RedirectRule, name string, line int) error {
	if !strings.HasPrefix(rule.From, "/") {
		return fmt.Errorf("%s:%d: source path must start with \"/\"", name, line)
	}
	if !strings.HasPrefix(rule.To, "/") {
		return fmt.Errorf("%s:%d: target path must start with \"/\"", name, line)
	}
	if rule.Status < 300 || rule.Status > 399 {
		return fmt.Errorf("%s:%d: status must be a 3xx integer", name, line)
	}

	fromHasSplat := strings.HasSuffix(rule.From, "/*")
	toHasSplat := strings.Contains(rule.To, ":splat")
	if strings.Contains(rule.From, "*") && !fromHasSplat {
		return fmt.Errorf("%s:%d: wildcard is only supported as a trailing \"/*\"", name, line)
	}
	if toHasSplat && !fromHasSplat {
		return fmt.Errorf("%s:%d: \":splat\" target requires a trailing source wildcard", name, line)
	}

	return nil
}

func stripRedirectComment(line string) string {
	if index := strings.Index(line, "#"); index >= 0 {
		return line[:index]
	}
	return line
}
