name: deploy

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

concurrency:
  group: main
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone info
        uses: actions/checkout@v4
        with:
          repository: alsosee/info
          path: info
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone media
        uses: actions/checkout@v4
        with:
          repository: alsosee/media
          path: media
          token: ${{ secrets.PKG_TOKEN }}

      - name: Run action
        uses: ./
        with:
          info: ./info
          media: ./media
          output: ./output
          media_host: https://media.alsosee.info
          search_host: https://search.alsosee.info
          search_api_key: ${{ secrets.MEILISEARCH_KEY }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.6.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=finder --branch=main --commit-dirty=true
