name: deploy-ru

on:
  repository_dispatch:
    types: [deploy-ru]
  workflow_dispatch:

concurrency:
  group: main-ru
  cancel-in-progress: false

jobs:
  deploy-ru:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone info
        uses: actions/checkout@v4
        with:
          repository: alsosee/ru
          path: info
          token: ${{ secrets.PKG_TOKEN }}

      - name: Clone media
        uses: actions/checkout@v4
        with:
          repository: alsosee/media-ru
          path: media
          token: ${{ secrets.PKG_TOKEN }}

      - name: Run action
        uses: ./.github/actions/ru
        with:
          info: ./info
          media: ./media
          output: ./output
          media_host: https://ru.media.alsosee.info
          search_host: https://search.alsosee.info
          search_api_key: ${{ secrets.MEILISEARCH_KEY }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3.4.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy output --project-name=finder-ru --branch=main --commit-dirty=true
