name: schema

on:
  push:
    branches:
      - main
    paths:
      - "structs/content.go"
  workflow_dispatch:

jobs:
  schema:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger schema update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PKG_TOKEN }}
          repository: alsosee/search
          event-type: schema
