name: worker

on:
  push:
    branches:
      - main
    paths:
      - worker/**
      - .github/workflows/worker.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy --config worker/wrangler.toml
