name: worker consumers

on:
  push:
    branches:
      - main
    paths:
      - worker/**
      - .github/workflows/worker.yml
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Trigger info finder rebuild
        uses: peter-evans/repository-dispatch@v4.0.1
        with:
          token: ${{ secrets.PKG_TOKEN }}
          repository: alsosee/info
          event-type: finder
          client-payload: '{"trigger": "finder-worker", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
